### ISSUE TITLE
strange results of instance segmentation

### ISSUE THREAD

**Issue by Ishmael-7** [microsoft/X-Decoder#26]
Hello, thank you for your great work! I encountered some strange errors when running the code with COCO images.  I used the **BestSegTiny model** for **open vocabulary instance segmentation**, and most of the examples worked very well. However, when it came to categories like "man", "woman", "boy", "girl", "guy", strange results were generated. Especially, "man" is always recognized as "sky". 
I'm not sure what caused this error, and I'm wondering if using a larger model would correct the results? I'm looking forward to the release of new ckpts.
![pic1](https://user-images.githubusercontent.com/61551015/224655636-200b380f-74c2-4837-b797-52a798a40ece.png)
![pic2](https://user-images.githubusercontent.com/61551015/224655728-334f8ddf-f3fc-4426-910a-42138c939823.png)

**Comment by jwyang** [comment]
can you share the original image and text inputs for the above results?

**Comment by Ishmael-7** [comment]
![1](https://user-images.githubusercontent.com/61551015/225900341-cfad4fc6-87ec-492b-b56e-3868d7f1b5ad.png)
![2](https://user-images.githubusercontent.com/61551015/225900355-10019b27-67d5-48c4-a085-7e1bdb7c23d1.png)
![3](https://user-images.githubusercontent.com/61551015/225900360-15bd2d68-5152-4b01-bf6e-fffa0072fed2.png)
![4](https://user-images.githubusercontent.com/61551015/225900367-20294bde-5da2-4919-a31f-66dd289fbd5b.png)
Here are the original images from COCO. I entered only one word in the text input each time, such as 'man', 'woman', etc. Additionally, I attempted the All-in-One Demo, but encountered the same issue once more. I noticed that the words "man", "woman", "boy", "girl", and "guy" seem to cause issues more frequently than other words.
![man_error](https://user-images.githubusercontent.com/61551015/225903725-50f22dce-0743-48f8-9bbb-be10612826b9.png)
![girl_error](https://user-images.githubusercontent.com/61551015/225903732-f8632620-b727-4013-8c01-1b4af1851a47.png)

**Comment by MaureenZOU** [comment]
Thanks so much for your interest in our work and your patience in crop those results! Your usage is correct and inspiring. I think the result is caused by the natural task gap and the training 
<img width="1637" alt="Screenshot 2023-03-18 at 12 22 59 PM" src="https://user-images.githubusercontent.com/11957155/226123130-988ebb2a-9ef6-4638-84f1-f02fb5d6f1c8.png">
procedure gap between instance segmentation and referring segmentation. For example, girl/man these kinds of queries are closer to referring to segmentation instead of instance segmentation. Please see the following results:

<img width="1560" alt="Screenshot 2023-03-18 at 12 23 39 PM" src="https://user-images.githubusercontent.com/11957155/226123148-6f90a51b-5b8f-4abc-af99-98b8cdb8a467.png">
<img width="1637" alt="Screenshot 2023-03-18 at 12 22 59 PM" src="https://user-images.githubusercontent.com/11957155/226123151-01fbc434-bae5-4248-bb4a-4c27d8de35aa.png">


<img width="1615" alt="Screenshot 2023-03-18 at 12 30 03 PM" src="https://user-images.githubusercontent.com/11957155/226123227-44889632-41aa-48d4-b5e7-ec74b33c6d85.png">
<img width="1572" alt="Screenshot 2023-03-18 at 12 30 39 PM" src="https://user-images.githubusercontent.com/11957155/226123231-cc01b386-2bcd-4e73-a9be-cf0ac3fe383a.png">
